### ISSUE TITLE
Problems when compiling r2frida with make

### ISSUE THREAD

**Issue by enovella** [nowsecure/r2frida#101]
If r2pm is used to install r2frida no problems are found. However, when compiling the project I encounter this error:

```sh
$ r2 frida:///bin/ls
[r] Cannot open 'frida:///bin/ls'
```

If you uninstall it with r2pm, the error is the same:
```sh
$ r2pm -u r2frida
Already up to date.
Uninstall Done For r2frida
rm -f /"/home/edu/.local/share/radare2/plugins/io_frida.so"
$ r2 frida:///bin/ls
[r] Cannot open 'frida:///bin/ls'
```
Therefore, the manual compilation misses something.

**Comment by trufae** [comment]
Use `R_DEBUG=1 r2 -L ` to determine why the plugin can't be found

**Comment by trufae** [comment]
its expected to get this error if the plugin is not installed

**Comment by enovella** [comment]
My bad! Forgot to install it

**Comment by Tasfa** [comment]
what plugin？

**Comment by radare** [comment]
r2frida is a plugin

**Comment by 4LanP1** [comment]
Hi radare,
My installed radare2 that cannot open frida.
I installed the r2frida plugin:

R_DEBUG=1 r2 -L
...
rw_  frida    frida:// io plugin (MIT)

Environment Information: 

<img width="630" alt="Screen Shot 2020-09-05 at 14 33 13" src="https://user-images.githubusercontent.com/38803203/92300419-c4851900-ef84-11ea-8680-7765056f6039.png">

Kindly help me troubleshooting

**Comment by trufae** [comment]
The variable is R2_DEBUG

**Comment by jtibaquira** [comment]
Hi
I'm trying to load the r2frida plugin but I get some errors.

I use r2 from git and I installed the plugin using r2pm commands.
these are the outputs of the terminal. 

<img width="881" alt="Screen Shot 2020-12-14 at 12 34 52 PM" src="https://user-images.githubusercontent.com/263858/102115029-f5d57680-3e08-11eb-818d-5f093dfb942e.png">
<img width="727" alt="Screen Shot 2020-12-14 at 1 08 54 PM" src="https://user-images.githubusercontent.com/263858/102118359-96c63080-3e0d-11eb-930e-41d3721424a3.png">
<img width="730" alt="Screen Shot 2020-12-14 at 1 08 38 PM" src="https://user-images.githubusercontent.com/263858/102118363-975ec700-3e0d-11eb-8e84-d1a03a2223a1.png">
<img width="850" alt="Screen Shot 2020-12-14 at 1 10 14 PM" src="https://user-images.githubusercontent.com/263858/102118486-c07f5780-3e0d-11eb-8c46-bc6885c30244.png">
<img width="922" alt="Screen Shot 2020-12-14 at 1 10 04 PM" src="https://user-images.githubusercontent.com/263858/102118490-c117ee00-3e0d-11eb-8365-b5b656829012.png">

**Comment by enovella** [comment]
Hi @jtibaquira,

How are you "loading" the r2frida plugin? What are you exactly trying to  achieve?

**Comment by enovella** [comment]
Can you execute this command? @jtibaquira 
```sh
$ r2 frida://0
 -- Everybody hates warnings. Mr. Pancake, tear down this -Wall
[0x00000000]> 
```

**Comment by enovella** [comment]
You can take a crack at this [wiki](https://github.com/enovella/r2frida-wiki/blob/master/README.md)

**Comment by trufae** [comment]
You are using deprecated uris. Please check the r2 “frida://?” Help message

**Comment by jtibaquira** [comment]
> You are using deprecated uris. Please check the r2 “frida://?” Help message

thanks, @trufae @enovella, yes I was using deprecated uris, now is working. 
<img width="977" alt="Screen Shot 2020-12-14 at 3 04 46 PM" src="https://user-images.githubusercontent.com/263858/102129712-cf6e0600-3e1d-11eb-9f05-c4cb7cb8b9ad.png">
<img width="981" alt="Screen Shot 2020-12-14 at 3 05 06 PM" src="https://user-images.githubusercontent.com/263858/102129717-d3018d00-3e1d-11eb-808d-c70009a1a20f.png">
