### ISSUE TITLE
Installation failed on Mac -  

### ISSUE THREAD

**Issue by exrme18** [nowsecure/r2frida#105]
Hello,
While installing the r2frida I am getting the following error. I was able to use r2frida earlier on same system.  

`Manish:~ manish$ r2pm -i r2frida
Already up to date.
Install Done For r2frida
[ "`readlink ext/frida`" = frida-macos-12.2.6 ] || \
		(cd ext && rm -f frida ; ln -fs frida-macos-12.2.6 frida)
make io_frida.dylib
cc -c -fPIC -I/usr/local/include/libr -DWITH_CYLANG=0 -Iext/frida src/io_frida.c -o src/io_frida.o
src/io_frida.c:263:58: error: use of undeclared identifier 'R_PERM_RWX'
        return r_io_desc_new (io, &r_io_plugin_frida, pathname, R_PERM_R...
                                                                ^
1 error generated.
make[1]: *** [src/io_frida.o] Error 1
make: *** [all] Error 2
ERROR: Build failed
Manish:~ manish$ r2 frida://c0ddef4bd7133b34caf39191231a8bc0b0dd5c43//Gadget
[r] Cannot open 'frida://c0ddef4bd7133b34caf39191231a8bc0b0dd5c43//Gadget'
Manish:~ manish$ r2
r2       r2agent  r2pm
Manish:~ manish$ r2
r2       r2agent  r2pm
Manish:~ manish$ r2 frida://Skype
[r] Cannot open 'frida://Skype'
`

<img width="912" alt="screenshot 2018-10-08 at 10 22 06 pm" src="https://user-images.githubusercontent.com/40659223/46622702-13339980-cb49-11e8-83c2-2f61cd99bff1.png">

Frida version: 12.2.9 
Latest Mac OS running. 

Thanks.

**Comment by enovella** [comment]
Perhaps it works if you try to edit the `Makefile` and adjust the frida version to 12.2.9. Compile as documented in the `README.md`

**Comment by enovella** [comment]
Hi @exrme18,

please update your radare2. There was a change that affects precisely that at commit https://github.com/nowsecure/r2frida/commit/ef4a04104097eb34b8d1c5c4e2cfbf440cd0efd1
