### ISSUE TITLE
r2frida crashes executing \di

### ISSUE THREAD

**Issue by AdriVillaB** [nowsecure/r2frida#107]
### Setup

- Frida-server: 12.2.18 (iOS)
- Mobile: iPhone 5S with iOS 10.2
- Last version of r2frida installed using r2pm
- Radare2 pulled from git

### Problem
I'm trying to use \di[0,1,-1] and after executing it, r2 crashes due to a segmentation fault. 

###Valgrind
I executed r2 using Valgrind and it generated the next output

valgrind r2 frida://32d43d5aee3c26f46e1928c7e82989ccae7e16ed/DVIA
==27958== Memcheck, a memory error detector                
==27958== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==27958== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==27958== Command: r2 frida://32d43d5aee3c26f46e1928c7e82989ccae7e16ed/DVIA
==27958==
[0x00000000]> \di0 0x0000000100203808
==27958== Invalid read of size 4
==27958==    at 0xB710890: _frida_json_node_get_node_type (json-node.c:1236)
==27958==    by 0xB70FD27: _frida_json_object_get_string_member (json-object.c:778)
==27958==    by 0xB6EA191: __system (in /home/adri/.local/share/radare2/plugins/io_frida.so)
==27958==    by 0x70EB4A5: r_io_system (io.c:443)
==27958==    by 0x5140098: cmd_rap_run (cmd.c:609)
==27958==    by 0x518E3FE: r_cmd_call (cmd_api.c:239)
==27958==    by 0x5146E66: r_core_cmd_subst_i (cmd.c:2929)
==27958==    by 0x5143D2C: r_core_cmd_subst (cmd.c:1937)
==27958==    by 0x514936A: r_core_cmd (cmd.c:3650)
==27958==    by 0x50B75B9: r_core_prompt_exec (core.c:2648)
==27958==    by 0x10F90C: main (radare2.c:1442)
==27958==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==27958== 
==27958== 
==27958== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==27958==  Access not within mapped region at address 0x0
==27958==    at 0xB710890: _frida_json_node_get_node_type (json-node.c:1236)
==27958==    by 0xB70FD27: _frida_json_object_get_string_member (json-object.c:778)
==27958==    by 0xB6EA191: __system (in /home/adri/.local/share/radare2/plugins/io_frida.so)
==27958==    by 0x70EB4A5: r_io_system (io.c:443)
==27958==    by 0x5140098: cmd_rap_run (cmd.c:609)
==27958==    by 0x518E3FE: r_cmd_call (cmd_api.c:239)
==27958==    by 0x5146E66: r_core_cmd_subst_i (cmd.c:2929)
==27958==    by 0x5143D2C: r_core_cmd_subst (cmd.c:1937)
==27958==    by 0x514936A: r_core_cmd (cmd.c:3650)
==27958==    by 0x50B75B9: r_core_prompt_exec (core.c:2648)
==27958==    by 0x10F90C: main (radare2.c:1442)

**Comment by enovella** [comment]
Hi,

Thanks for opening a ticket. Could you please share the app you are testing with? 
Also, is the process resumed, paused or was just attached?  From the URI, it seems you're attaching to the app, doesn't it?

Cheers

**Comment by AdriVillaB** [comment]
Hi @enovella ,

I was using the DVIA app, just to show a friend how r2frida works. I was attached to a running application, not spawning it.

One teammate test the same on one real application, and it crashes too.

Cheers

**Comment by mrmacete** [comment]
nice bug! thanks for reporting. just reproduced, i'll look into this.

**Comment by AdriVillaB** [comment]
Welcome @mrmacete . Thanks for the fix :)
