### ISSUE TITLE
Tracing basic blocks

### ISSUE THREAD

**Issue by radare** [nowsecure/r2frida#110]
Ease the way define one trace for each basic block in a function and set the dt (debug trace hints) inside r2, this way we can use the graph.trace with Frida as backend

**Comment by trufae** [comment]
we can do that already with a oneliner iterating over all bbs of current function and setting a trace on each no need for a specific command imho

**Comment by trufae** [comment]
cc @as0ler  i would fix that with documentation or an r2frida plugin instead
