### ISSUE TITLE
"expected a NativePointer object"

### ISSUE THREAD

**Issue by bannsec** [nowsecure/r2frida#111]
In playing with r2frida and following the r2con talk about it, i was trying the `\dxc` command. Unfortunately, it only errors out for me with this error:

```
[0x00000000]> \dxc main
expected a NativePointer object

[0x00000000]> \dmas "Hello world"
0x7f6ca2357a60

[0x00000000]> \dxc main 0x7f6ca2357a60
expected a NativePointer object
```

I'm using the pip version of r2rfrida and this r2:

```
radare2 3.4.0-git 1 @ linux-x86-64 git.3.4.0-git
commit: 8e1da330b64f4c83b8f0cc9697ba635304ce1ce6 build: 2019-03-08__06:10:25
```

**Comment by mrmacete** [comment]
probably `main` is not a symbol, try to see what symbols you get with `\is` and if `main` is among them, and/or use the address instead of the name if you know it

**Comment by trufae** [comment]
Even if the symbol name is not there i agree that the error message should be more  friendly

**Comment by oleavr** [comment]
Typically this means `Module.findExportByName()` is used instead of `Module.getExportByName()`.
