### ISSUE TITLE
ReferenceError when running scripts from r2Frida environment

### ISSUE THREAD

**Issue by maqsoodahmadjan** [nowsecure/r2frida#152]
I get a ReferenceError when I run a sample script from r2Frida environment on the latest version. 

`Java.perform(function(){
^

ReferenceError: Java is not defined
    at Object.<anonymous> (/Users/maqsood/Frida/script.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11`

**Comment by trufae** [comment]
which sample sccript, how are you running this script, which r2frida
environment? this script is not suposed to be executed outside r2frida, and
r2frida loads it directly, so you dont have to do anything

**Comment by maqsoodahmadjan** [comment]
Sample script:

Java.perform(function(){
	console.log("Hello World");
});

r2Frida Environment:
By r2Frida environment, I meant when an app is launched using r2Frida.

Running the script:
Using the `.` operator and specifying the path to the .js file.

**Comment by trufae** [comment]
The . Command runs script inside r2 in host. This is, with nodejs. What you want to use is the \. Which loads and runs the script in the agent side

**Comment by maqsoodahmadjan** [comment]
Yes. You are right. I thought it was without a slash and the error might be coming from somewhere else. Sorry for the trouble.
