### ISSUE TITLE
Repo Update Needed

### ISSUE THREAD

**Issue by vF-kproctor** [nowsecure/r2frida#2]
### Overview

We are asking that you update your Repo to address the issues below.  If this Repo is no longer being used please indicate that in a comment below.
- [x] Add a build badge to your README.md.
- [ ] Add a dependencies badge to your README.md (`npm-dm.nowsecure.io`).
- [ ] Your repo does not have any tests.  Add your tests as well as what framework you are using.
- [ ] Update your dependencies.

**Comment by trufae** [comment]
r2frida is now using CI with Travis and i put the badge, closing this 4yo issue as long as its no longer relevant
