### ISSUE TITLE
r2frida warning when hooking to process

### ISSUE THREAD

**Issue by TheS0cialSheep** [nowsecure/r2frida#203]
Please help me support the hooking issues of R2frida :( 

Everytime i try to analysis the iOS Application with r2frida, it always return the following issue:
r2 frida://<device-id>/Headbook
WARNING: r_bin_open_buf: assertion '(st64)opt->sz >= 0' failed (line 250)

Information note: 
Server - Client Frida version: 12.7.26

When installing the r2frida, i saw it get version 12.7.14. Is it the root cause of the client. I try to manually compile but that is not effective.

**Comment by enovella** [comment]
What about this? Please check the help usage and choose your election. The 2nd command is my suggestion.

```c
$  r2 frida://?
$ r2 frida://spawn/usb//Headbook
```

**Comment by TheS0cialSheep** [comment]
Many thanks for your recommendation.
1 - use device id
<img width="606" alt="Screen Shot 2019-12-17 at 10 34 27 PM" src="https://user-images.githubusercontent.com/38803203/71009819-75106b80-211d-11ea-9932-622c9c4dbbbd.png">

2. as your suggestion:
<img width="646" alt="Screen Shot 2019-12-17 at 10 36 13 PM" src="https://user-images.githubusercontent.com/38803203/71009916-a426dd00-211d-11ea-8280-a6804c6f0884.png">

I tried on all my devices : ipad mini 2 and iphone 6.

**Comment by enovella** [comment]
You don't have r2frida installed, do you?

Verify it with:

```sh
$ r2 -L|grep -i frida
rw_  frida    frida:// io plugin (MIT)
```

**Comment by TheS0cialSheep** [comment]
I already installed it as r2frida github recommendation.

<img width="367" alt="Screen Shot 2019-12-17 at 11 30 01 PM" src="https://user-images.githubusercontent.com/38803203/71014922-4f876000-2125-11ea-9d31-704b8db65df3.png">

**Comment by enovella** [comment]
The iOS appname is not correct.

**Comment by TheS0cialSheep** [comment]
Dear enovella.
This is an ctf mobile apps.
I have just perform full step.
![Screen Shot 2019-12-18 at 4 42 22 PM](https://user-images.githubusercontent.com/38803203/71074737-5fe71b80-21b5-11ea-82ae-94baa2e520ed.png)

**Comment by radare** [comment]
Which version of r2 are you using?

**Comment by trufae** [comment]
This warning is because r2 is trying to parse a binary from memory of a 64bit address space in size which is obv not correct. Afaik this was fixed several months ago

**Comment by TheS0cialSheep** [comment]
> Which version of r2 are you using?
> […](#)
> On 18 Dec 2019, at 18:42, TheS0cialSheep ***@***.***> wrote: ﻿ Dear enovella. This is an ctf mobile apps. I have just perform full step. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

My Radare2 version:
radare2 4.1.0-git 23289 @ darwin-x86-64 git.4.0.0-226-g89a5320e5
commit: 89a5320e5f918327f6f528fa325eeef6567932a8 build: 2019-12-16__11:27:08

**Comment by TheS0cialSheep** [comment]
> This warning is because r2 is trying to parse a binary from memory of a 64bit address space in size which is obv not correct. Afaik this was fixed several months ago
> […](#)
> On 17 Dec 2019, at 15:37, TheS0cialSheep ***@***.***> wrote: ﻿ Please help me support the hooking issues of R2frida :( Everytime i try to analysis the iOS Application with r2frida, it always return the following issue: r2 frida:///Headbook WARNING: r_bin_open_buf: assertion '(st64)opt->sz >= 0' failed (line 250) Information note: Server - Client Frida version: 12.7.26 When installing the r2frida, i saw it get version 12.7.14. Is it the root cause of the client. I try to manually compile but that is not effective. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi  trufae, my radare2 version is the lastest. So why is it still have a issues? Can you help me?

**Comment by trufae** [comment]
That's a harmless warning, you shouldnt be worried about it, everything  should be working fine
