### ISSUE TITLE
unable to find module 'libfooLib.so'

### ISSUE THREAD

**Issue by onegithuber** [nowsecure/r2frida#205]
`r2 frida://031eceafd0241e51/com.goodl.aes.test

ctx.getDataDir is not a function

WARNING: r_bin_open_buf: assertion '(st64)opt->sz >= 0' failed (line 250)

ctx.getDataDir is not a function

 -- I endians swap.`

`\iE* libfooLib.so
unable to find module 'libfooLib.so'`

**Comment by trufae** [comment]
the rbuf warning is a known thing u can ignore, the \iE command works fine here, is this lib listed in \il ?

**Comment by Tasfa** [comment]
ctx.getDataDir is not a function
WARNING: r_bin_open_buf: assertion '(st64)opt->sz >= 0' failed (line 250)
ctx.getDataDir is not a function
 -- Ilo ni li pona li pali e lipu. mi wile e ni: sina kama jo e musi

[0x00000000]> \i
ctx.getDataDir is not a function

**Comment by radare** [comment]
Which version of android is the device you are attaching to?

**Comment by trufae** [comment]
getDataDir() is only available on Android7 and above. i have added a check to avoid this to make r2frida fail. `r2pm -ci r2frida` again please

**Comment by trufae** [comment]
Should be fixed now
