### ISSUE TITLE
Error while installing r2frida

### ISSUE THREAD

**Issue by roopeshiitd** [nowsecure/r2frida#207]
I'm trying to install r2frida using r2pm -ci r2frida and facing the below error.

I have the latest version of radare2.
radare2 4.3.0-git 0 @ linux-x86-64 git.4.3.0-git
commit: HEAD build: 2020-01-29__21:16:13

**Error:**
> r2frida-agent@3.9.0 build /home/roopesh/.local/share/radare2/r2pm/git/r2frida
> frida-compile src/agent -o src/_agent.js

xxd -i < src/_agent.js > src/_agent.h
cc -c -fPIC -g -I/usr/include/libr -DWITH_CYLANG=0 -Iext/frida src/io_frida.c -o src/io_frida.o
src/io_frida.c:3:10: fatal error: r_core.h: No such file or directory
 #include <r_core.h>
          ^~~~~~~~~~
compilation terminated.
Makefile:155: recipe for target 'src/io_frida.o' failed
make[1]: *** [src/io_frida.o] Error 1
make[1]: Leaving directory '/home/roopesh/.local/share/radare2/r2pm/git/r2frida'
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: Build failed

**Comment by radare** [comment]
From what i see in the error message your installation of r2 is incomplete. The missing include should be available after installing r2. Which looks installed from git.. but maybe you are also using debian and you didnt uninstalled the radare pkg from system?
