### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by SPlayer1248** [nowsecure/r2frida#210]
I run and got this error message.

> $r2 frida://usb//2367 
Module version mismatch /home/username/.local/share/radare2/plugins/io_frida.so (4.3.0-git) vs (4.2.1)
r2pm -ci r2frida
[r] Cannot open 'frida://usb//2367'

I tried both 2 ways to install (git, r2pm) and got the same error.

**Comment by trufae** [comment]
Try removing the offending plugin first. I assume you did make install as root at some point and it failed to replace the old plugin

**Comment by SPlayer1248** [comment]
I already removed all plugins and fresh installed both radare2 and r2frida but nothing worked

**Comment by enovella** [comment]
Did you install radare2 from git? If so, then try this out:
```sh
$ sudo apt remove radare2
$  r2pm -ci r2frida
```

**Comment by SPlayer1248** [comment]
I tried but it not work :(

![remove](https://user-images.githubusercontent.com/24432650/75209895-5f7a7c00-5734-11ea-99ad-8464ee256457.png)
![install](https://user-images.githubusercontent.com/24432650/75209894-5e494f00-5734-11ea-848e-118e5f344a3f.png)
![run](https://user-images.githubusercontent.com/24432650/75209898-60aba900-5734-11ea-95ec-efbe752485e6.png)

**Comment by enovella** [comment]
try this 

`$ r2 frida://0`

The problem i think is the way you're using the tool.

**Comment by enovella** [comment]
Also, you should update your radare2 to the latest

**Comment by SPlayer1248** [comment]
This is the latest version of my os

![r2](https://user-images.githubusercontent.com/24432650/75211555-1da00480-5739-11ea-93b2-e2f4cccab2c9.png)

**Comment by trufae** [comment]
Latest r2 = r2 from git, aka 4.3

**Comment by SPlayer1248** [comment]
Thanks! I fixed!
