### ISSUE TITLE
error when install r2frida on windows10

### ISSUE THREAD

**Issue by litttley** [nowsecure/r2frida#215]
I encountered the following error when installing

`
> r2frida-agent@3.9.0 prepare D:\software\r2frida-4.2.0
> npm run build

> r2frida-agent@3.9.0 build D:\software\r2frida-4.2.0
> frida-compile src/agent -o src/_agent.js

{ Error: Cannot find module '../../ext/swift-frida/examples/r2swida/index.js' from 'D:\software\r2frida-4.2.0\src\agent'
    at D:\software\r2frida-4.2.0\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (D:\software\r2frida-4.2.0\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (D:\software\r2frida-4.2.0\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at D:\software\r2frida-4.2.0\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
`

platform:windows10
node: v10.15.3
source:r2frida-4.2.0
radare2: radare2_installer-msvc_64-3.2.1.exe

**Comment by radare** [comment]
R2 3.2 is 1 year old. It wont build because you need the same version of r2 and r2frida
