### ISSUE TITLE
DetachReason: FRIDA_SESSION_DETACH_REASON_PROCESS_TERMINATED

### ISSUE THREAD

**Issue by Dev-Bobbie** [nowsecure/r2frida#218]
Setup:
Frida-server v12.8.15 arm64
Mobile: xiaomi5s arm64
Android versio 6.0.1
r2frida compiled with frida 12.8.10
Radare2 pulled from git
Macos 10.15.2
Problem:
When i use r2 frida://bccd63f3/com.xiaojianbang.app commands to connect my devices,the terminal show as below:
DetachReason: FRIDA_SESSION_DETACH_REASON_PROCESS_TERMINATED
Target process terminated
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
arning: r_bin_file_hash: file exceeds bin.hashlimit
error: Script is destroyed
Can you give me some suggestions? i try upgrade android version to 9.0,but the problem still appear

**Comment by enovella** [comment]
Try this:

```sh
r2 frida://spawn/usb//com.xiaojianbang.app
```

**Comment by Dev-Bobbie** [comment]
r2 frida://spawn/usb/bccd63f3/com.xiaojianbang.app
DetachReason: FRIDA_SESSION_DETACH_REASON_PROCESS_TERMINATED
Target process terminated
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
Warning: r_bin_file_hash: file exceeds bin.hashlimit
error: Script is destroyed
 -- Use headphones for best experience.

r2 frida://spawn/usb/bccd63f3/com.xiaojianbang.app
DetachReason: FRIDA_SESSION_DETACH_REASON_PROCESS_TERMINATED
Target process terminated
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
Warning: r_bin_file_hash: file exceeds bin.hashlimit
error: Script is destroyed
 -- Step through your seek history with the commands 'u' (undo) and 'U' (redo)
[0x00000000]>
[0x00000000]>
[0x00000000]> exit

**Comment by Dev-Bobbie** [comment]
Hi,
Is there any solution？

**Comment by enovella** [comment]
Android 6.0 seems to be old. Going to try on my setup with Android 9 & 10

**Comment by radare** [comment]
Is frida by itself working fine on this setup? I cant reproduce but i assume there’s something in the agent.js that is making it cry

**Comment by Dev-Bobbie** [comment]
> Is frida by itself working fine on this setup? I cant reproduce but i assume there’s something in the agent.js that is making it cry
> […](#)
> On 26 Mar 2020, at 13:21, Dev-Bobbie ***@***.***> wrote: ﻿ Hi, Is there any solution？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

frida work  fine

**Comment by trufae** [comment]
Can you try the same thing on newer androids? the oldest one i have around is android7 and i cant reproduce. This error happens when frida-agent crashes. If Frida itself is not crashing is maybe related to something that is doing the r2frida's agent script. Could you try to comment lines in there and see if that makes it not fail?.

Maybe I can add a failsafe mode for r2frida to debug this kind of issues

**Comment by trufae** [comment]
is the target process  32 or 64 bit? because im having this issue when attaching to 32bt arm processes on android10

**Comment by trufae** [comment]
i've tracked down the issue to get the frida reproducer. The crash happens when trying to read 4 bytes at address 8, you can get the same crash like this:

```
$ frida -U -p $pidof.com.android.chrome
-> Memory.readByteArray(ptr(8), 4)
```

So it's an issue in frida server's Exceptor for android/thumb.

From the r2frida side i did a workaround that is now available on master. Run r2 like this:

```
R2FRIDA_SAFE_IO=1 r2 frida://usb//pid
```

**Comment by trufae** [comment]
i would like to close all those issues in r2frida, because that's a bug in Frida.

Follow the frida bug in https://github.com/frida/frida-gum/issues/422
