### ISSUE TITLE
pdf_command_error

### ISSUE THREAD

**Issue by 18345093167** [nowsecure/r2frida#228]
![pdf_command_error](https://user-images.githubusercontent.com/20567891/80908077-79959380-8d4f-11ea-9b33-a0420dc17d13.png)

I use `r2 -d frida://BH93001BDE/com.lingpao.lpcf622b` to debug so file on Android 10, but when I try` pdf` command, the process is terminated. You can see it from picture.

**Comment by trufae** [comment]
This is a bug in Frida and you can workaround it r2frida with R2FRIDA_SAFE_IO=1 as env var

Also. No need to use -d, and you can use frida://usb// as uri to avoid having to type the deviceid

**Comment by 18345093167** [comment]
burning@burning-RedmiBook-14-APCS:~$ R2FRIDA_SAFE_IO=1 r2 frida://usb//21894
DetachReason: FRIDA_SESSION_DETACH_REASON_PROCESS_TERMINATED
CrashReport: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'KDDI/SOV39_jp_kdi/SOV39:10/52.1.C.0.217/052001C000021700726438165:userdebug/dev-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2020-05-03 17:10:16+0900
pid: 21894, tid: 22194, name: Thread-4  >>> com.android.chrome <<<
uid: 10272

**Comment by 18345093167** [comment]
I have found the workaround "R2FRIDA_SAFE_IO=1 r2 frida://usb//21894" is valid sometimes, but sometimes it is invalid. I will check it further.
