### ISSUE TITLE
Cannot attach: The connection is closed

### ISSUE THREAD

**Issue by ghost** [nowsecure/r2frida#234]
each time connecting to server ,it will crash with this error

**Comment by trufae** [comment]
Can you please describe the version of r2, r2frida and the command you are using to get this error?

Thanks!

**Comment by oxpy** [comment]
I cloned r2frida  from this repo ,and make install it ,is it the newest version ?
r2 -v :  radare2 4.5.0-git 24673 
frida version is 10.9.4

**Comment by trufae** [comment]
And how did you executed r2 to get this error? Which OS and arch?

**Comment by oxpy** [comment]
on ubuntu 20.04 LTS
r2 frida://deviceid/com.xxx.app

**Comment by radare** [comment]
use the right URI expression:

r2 frida://attach/usb/$(device)/$(target)

so you can do it lie this:

r2 frida://attach/usb//com.xxx.app

**Comment by oxpy** [comment]
it is the same .

Cannot attach: The connection is closed

**Comment by radare** [comment]
Are you still able to reproduce the crash? because i dont :/

**Comment by 56byte** [comment]
same problem.

r2 frida: //attach/usb//com.xxx.app
_Cannot attach: Unable to connect to remote frida-server: Connection closed_

**Comment by trufae** [comment]
Is this happening with latest r2 and r2frida from git?

**Comment by enovella** [comment]
Please update. Working well on Android on my end
