### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by oxpy** [nowsecure/r2frida#235]
src/io_frida.c:449:5: error: ‘RIO’ {aka ‘struct r_io_t’} has no member named ‘corebind’

**Comment by radare** [comment]
Which version of r2 do you use?

**Comment by oxpy** [comment]
r2 -version
radare2 4.2.1 0 @ linux-x86-64 git.4.2.1

**Comment by radare** [comment]
You need r2-4.4 at least

**Comment by oxpy** [comment]
ok ,resolved !
but when connecting to device process ,it report connection closed ,and the running app crashed at the same time
