### ISSUE TITLE
DetachReason: FRIDA_SESSION_DETACH_REASON_PROCESS_TERMINATED

### ISSUE THREAD

**Issue by ghost** [nowsecure/r2frida#236]
r2 -version
radare2 4.5.0-git 24673 @ linux-x86-64 git.4.4.0-201-ga103293ec

fridaserver version : 12.9.3

**Comment by trufae** [comment]
Please update to the latest r2 and latest frida, the issue here was probably caused by a bug in frida when accessing unmapped memory. and that was fixed a while ago. Sorry for the late response. Please come back and comment if you are still having issues here
