### ISSUE TITLE
windows install failed,please update build.bat

### ISSUE THREAD

**Issue by tmxd09887** [nowsecure/r2frida#239]
follow the readme
build.bat install
but got error
```

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! r2frida-agent@4.5.0 build: `frida-compile -L -c src/agent -o src/_agent.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the r2frida-agent@4.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dd\AppData\Roaming\npm-cache\_logs\2020-06-10T06_44_16_020Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! r2frida-agent@4.5.0 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the r2frida-agent@4.5.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dd\AppData\Roaming\npm-cache\_logs\2020-06-10T06_44_16_220Z-debug.log
cat: '.\_agent.js': No such file or directory
Compiling...
```

`“frida-core.h”: No such file or directory`

**and the frida version is out date(12.6.23)**

**Comment by vmprog** [comment]
The same problem on Windows 7
frida 12.8.20
r2frida 4.3.1

**Comment by trufae** [comment]
I don't see anything relevant in the logs and i don't have any windows machine to try it out. Anyone using windows can have a look at this issue? @oleavr ?

Now with github actions, i should setup the per-commit builds for windows too

**Comment by vmprog** [comment]
Added command prompt output:
[error.log](https://github.com/nowsecure/r2frida/files/4804078/error.log)

**Comment by trufae** [comment]
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'

this seems relevant. But i dont see why npm dependencies should be
different in windows or mac/Linux. Can you confirm the frida sdk is
downloaded properly? the initial error was a missing frida.h

**Comment by vmprog** [comment]
That's right I understand what I need to install Windows Toolchain and SDK from
https://frida.re/docs/building/#windows
$ git clone --recurse-submodules https://github.com/frida/frida
$ cd frida
$ py -3 releng\build-deps-windows.py

**Comment by oleavr** [comment]
@vmprog That's not necessary. The r2frida build system downloads a prebuilt devkit from https://github.com/frida/frida/releases, which contains a header and a static library.
