### ISSUE TITLE
wherer is the used js script file stored when it communicate with frida?

### ISSUE THREAD

**Issue by w0x12e** [nowsecure/r2frida#242]
I think it will send js file to work with frida.If I editing the js file ,that could be convinient

**Comment by w0x12e** [comment]
for example.  this command  \iE ,what does it tell frida to do ?

**Comment by trufae** [comment]
if you are fixing a bug in r2frida, just `npm run build; make install` for each run, the js file sent is generated and compiled via frida-compile, so you cant edit it by hand.

If you want to see what iE do just read src/agent/index.js and search for `iE`
