### ISSUE TITLE
Build failed on MacOS

### ISSUE THREAD

**Issue by siddharthsyal** [nowsecure/r2frida#257]
I am trying to install r2frida using "r2pm -ci r2frida". But I am getting the following error message and the build fails.

![r2Frida_build_failed](https://user-images.githubusercontent.com/40547786/93396779-317e9580-f846-11ea-8cc7-5752b7a1c9e0.jpg)

**Comment by trufae** [comment]
How did you install r2? It seems like you have an old version

**Comment by siddharthsyal** [comment]
@trufae Sorry. I missed that. I updated the R2 version and the error got fixed.
