### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by FFeliziani** [nowsecure/r2frida#261]
Hi, I've just installed the latest LTS version of Ubuntu desktop on my machine (kernel version 5.8.14-surface), 
installed Frida from pip 
`$: frida --v`
`12.11.18`
installed rarare2 from apt
`$: r2 -v`
`radare2 4.2.1 @ linux-x86-64 git.4.2.1`
and run `r2pm init`.

When I try and install r2frida with `r2pm -ci r2frida` I get the following output:

[output.log](https://github.com/nowsecure/r2frida/files/5393324/output.log)

Any ideas?

**Comment by trufae** [comment]
Upgrade r2. This one is too old

**Comment by FFeliziani** [comment]
Is there a PPA for an updated version through apt or should I use the github build?

**Comment by FFeliziani** [comment]
that's ok, i used the github build and it seems to work. Thanks!
