### ISSUE TITLE
Access violation accessing 0xd86aa000

### ISSUE THREAD

**Issue by 18345093167** [nowsecure/r2frida#271]
I really want to use r2frida to inspect android apk. But there is an issue as below, could you please help to resolve the problem. I use the latest release version on Ubuntu 20.04.

burning@burning-RedmiBook-14-APCS:~/wireless/CTF_repo-master/NDH2k12$ r2 frida://BH93001BDE/com.android.chrome
error: access violation accessing 0xd86aa000
DetachReason: FRIDA_SESSION_DETACH_REASON_PROCESS_TERMINATED
CrashReport: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Revision: '0'
ABI: 'arm'
Timestamp: 2020-11-10 13:11:06+0900
pid: 1739, tid: 2455, name: gum-js-loop >>> com.android.chrome <<<
uid: 10272
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xc0163bf4 (*pc=0x71b4f500)
r0 bfd5cfac r1 00000008 r2 00000004 r3 d826d200
r4 d828a218 r5 c7fe7280 r6 ffffffff r7 bfd5d140
r8 d834e370 r9 d83bf900 r10 00000008 r11 d826d208
ip 40000000 sp bfd5cf10 lr 00000539 pc c0163bf4

backtrace:
#00 pc 000febf4 /data/local/tmp/re.frida.server/frida-agent-32.so

Target process terminated
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed

...

**Comment by 18345093167** [comment]
The android version is 10.

**Comment by trufae** [comment]
This is a bug in Frida, not in r2frida. See in https://github.com/nowsecure/r2frida/issues/226 for instructions to workaround the crash
