### ISSUE TITLE
The app is frozen when using spawn mode

### ISSUE THREAD

**Issue by BurningTeng** [nowsecure/r2frida#275]
I use following command to spawn chrome app on android 10 device
`r2 frida://BH93001BDE//com.android.chrome`
**The app is frozen.**

Result as below:
burning@burning-RedmiBook-14-APCS:~/radare2$ r2 frida://BH93001BDE//com.android.chrome
 -- The Hard ROP Cafe
[0x00000000]>

**Comment by trufae** [comment]
the uri you are using is not correct. See `r2 frida://?` for help. you must use `frida://spawn/usb/deviceid/appname`

**Comment by 18345093167** [comment]
The result is same on Android 10.

burning@burning-RedmiBook-14-APCS:~/radare2$ r2 -d frida://spawn/usb/BH93001BDE/com.example.myapplication
 -- Try pressing the pigeon-shaped button
[0x00000000]>

**Comment by trufae** [comment]
The app has been spawned, and its frozen because if you use spawn it starts the app in suspend mode. if you want to continue the execution use the`=!dc` command or use the `launch` URI instead of `spawn`

**Comment by BurningTeng** [comment]
Thanks very much. I use command "=!dc". The process is resumed. 

Which command to use if I want "**launch URI instead of spawn**" you mentioned above. Following command?
r2 frida://BH93001BDE/com.android.chrome

**Comment by BurningTeng** [comment]
The spawn way looks great. I can hook method before Activity is started

**Comment by trufae** [comment]
`frida://launch/usb/deviceid/appname`

**Comment by BurningTeng** [comment]
Thanks very much.
