### ISSUE TITLE
Command \iE does not work

### ISSUE THREAD

**Issue by BurningTeng** [nowsecure/r2frida#276]
1. Attach process
`r2 frida://BH93001BDE/com.asp.lovevideo`
2. Using iE as [r2frida-wiki](https://github.com/enovella/r2frida-wiki)
`[0x00000000]> \iE`

Result as below:
Error message shown as below:
error: unable to find module containing 0x0

![burning](https://user-images.githubusercontent.com/20567891/100125777-1e2c1e00-2eb8-11eb-917b-1a5fcadef5dd.png)

**Comment by trufae** [comment]
All i subcommands depend on the offset. First seek to the address of the binary or library that u want to get the exports. Otherwise it would list milions of symbols. Thats why this behaviour has changed a year ago

**Comment by BurningTeng** [comment]
Thanks for your explanation.

**Comment by enovella** [comment]
Try:

```sh
\iE @ offset  //where offset is the base address of your native lib
```
