### ISSUE TITLE
command pdf can not work properly

### ISSUE THREAD

**Issue by BurningTeng** [nowsecure/r2frida#277]
1. Attach process
    r2 frida://BH93001BDE/com.asp.lovevideo
2. Using \iE libImSDK.so~nativeDoBackground
3. Using command pdf
Error message is shown as below:
p: Cannot find function at 0x76fdd59314
4. Using pd, it can work

![burning](https://user-images.githubusercontent.com/20567891/100127190-d73f2800-2eb9-11eb-8947-b7dac2ea4154.png)

**Comment by enovella** [comment]
You need to analyze function (`af`) before doing `pd` or `pdf`
```sh
s offset
af
pdf // or pdg (if you installed r2ghidra-dec)
```

**Comment by BurningTeng** [comment]
I tried pdz. It does not work. I will try pdz later.

[0x76fdd59318]> pdz
decompilation error: Failed to load input file

**Comment by trufae** [comment]
pdz is not a valid command. why do you want to use pdz?

**Comment by BurningTeng** [comment]
A command which is provided by r2Retdec plugin. It does not work.

I have tried pdg for decompiling. It works well.
But when I use command pdf, following message will show. **What is the meaning of following message?**
`Linear size differs too much from the bbsum, please use pdr instead.`
Command pdr and pdg works well.
![burning](https://user-images.githubusercontent.com/20567891/100170534-dc739580-2f00-11eb-89bc-a3a8a446b34f.png)

**Comment by enovella** [comment]
Try with r2ghidra-dec:

```sh
$ r2pm -ci r2ghidra-dec
```

```sh
$ r2 frida://BH93001BDE/com.asp.lovevideo
s `\iE @ libImSDK.so~+nativeDoBackground`
af
pdg
```

**Comment by BurningTeng** [comment]
Thanks very much. pdg works well.

But when I use command pdf, following message will show. **What is the meaning of following message?**
Linear size differs too much from the bbsum, please use pdr instead.

![burning](https://user-images.githubusercontent.com/20567891/100217128-10c17300-2f4e-11eb-8dc3-6eca0ce106fd.png)

**Comment by BurningTeng** [comment]
I have another question, Is there any method to make first parameter to be type JNIEnv?
![burning](https://user-images.githubusercontent.com/20567891/100221222-592f5f80-2f53-11eb-922e-9eea20535e2d.png)

**Comment by trufae** [comment]
this is an issue in r2 not r2frida, lets move the issue in the other project instead
