### ISSUE TITLE
Support Package Name Attaching

### ISSUE THREAD

**Issue by apkunpacker** [nowsecure/r2frida#328]
Frida server on localhost and random port -
./frida-server -l 127.0.0.1:1234

and in another Terminal -

```sh
$ r2 frida://attach/remote/127.0.0.1:1234/com.whatsapp
Process not found
[r] Cannot open 'frida://attach/remote/127.0.0.1:1234/com.whatsapp'
```

while

```sh
r2 frida://attach/remote/127.0.0.1:1234/whatsapp
```

works fine.
may be this is related to issue
https://github.com/nowsecure/r2frida/commit/bd6803e1f672d770e1c3da0ffbb2b35646359211

**Comment by enovella** [comment]
Can you please try this?

```sh
$ r2 frida://attach/connect/127.0.0.1:1234/com.whatsapp
```

**Comment by oleavr** [comment]
@apkunpacker The process name is typically different from the package name. This was among the breaking changes in Frida 15. (It's now consistent with the behavior on iOS.)

**Comment by as0ler** [comment]
com.whatsapp is the package name. You should use launch or spawn in the r2frida command line to make it work: 
<img width="488" alt="Screenshot 2021-08-19 at 19 22 30" src="https://user-images.githubusercontent.com/11234807/130115012-c37126bd-9a74-4f94-b31d-8653b635155e.png">

**Comment by apkunpacker** [comment]
> com.whatsapp is the package name. You should use launch or spawn in the r2frida command line to make it work:
> <img alt="Screenshot 2021-08-19 at 19 22 30" width="488" src="https://user-images.githubusercontent.com/11234807/130115012-c37126bd-9a74-4f94-b31d-8653b635155e.png">

launch and spawn working with package name but attaching not working

**Comment by as0ler** [comment]
Why do you need package name with Attach?  Is there any use case not already covered?
