### ISSUE TITLE
How to install r2frida in Windows 10

### ISSUE THREAD

**Issue by ganesh2183** [nowsecure/r2frida#336]
Need your help to install r2frida tool in windows 10 (64) environment.

Unable to install in windows environment, getting failed error message.

![16329200074733255812784921455150](https://user-images.githubusercontent.com/41476297/135272207-911ec1c8-bbbd-449f-94d7-6e4b13c48bd1.jpg)
![1632920036425655801044086912695](https://user-images.githubusercontent.com/41476297/135272310-3905efbf-5bf2-4db4-89c3-b500688e8eca.jpg)

Is it possible to install successfully in windows system.

**Comment by ganesh2183** [comment]
Could you please help on this

**Comment by oleavr** [comment]
Node.js is too old. Please upgrade it to 14 or 16.
