### ISSUE TITLE
error: Can't attach, launch, or spawn

### ISSUE THREAD

**Issue by hacker-jak** [nowsecure/r2frida#338]
I have a _rooted_ Android device with `frida-server-14+` running. The device is attached via usb, and I can see it with `frida-ls-devices`. I can also issue the `r2 "frida://apps/usb//"` command which works as expected.

The following spawn request gives an error. The same applies for a `launch` request.
```
$ r2 "frida://spawn/usb//<appname>"
Cannot spawn: Need Gadget to attach on jailed Android; its default location is: /home/jak/.cache/frida/gadget-android-arm64.so
```

Attaching to a running process results in an error as well.
```
$ r2 "frida://attach/usb//11407"
Cannot attach: Unable to connect to remote frida-server: Connection closed.
```
Though the server remains running.

Any help is appreciated, thanks.

```
$ frida --version
14.2.2
$ r2 -v
radare2 5.4.0 0 @ linux-x86-64 git.5.4.0
```

**Comment by enovella** [comment]
Upgrade to Frida 15.x please

**Comment by hacker-jak** [comment]
I updated `frida-server` to the latest version and that solved my issue. I wasn't aware that r2frida installed the latest release of frida for it's own use. I assumed it was using my system install.

Thank you for the reply!

**Comment by trufae** [comment]
R2frida build against the version of frida specified in the makefile. Right now this is frida15. But protocol changes over major versions so its common issue to break if mixing versions. You can pass the version of frida as argument when building

r2frida uses the frida sdk so if u run r2frida locally in the device you dont need the frida-server. But thats needed for usb or tcp links at least :)

closing the issue as long as its working for you.
