### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by solitudecc** [nowsecure/r2frida#346]
What's the problem with this?
![2021-11-06 17-46-01屏幕截图](https://user-images.githubusercontent.com/45167439/140605410-1eeb3d17-896a-4f0e-a051-a06ec3e2758c.png)

**Comment by enovella** [comment]
Is `:px` an R2frida command? Check these by typing `:?`

**Comment by solitudecc** [comment]
no

**Comment by solitudecc** [comment]
If you use`:` How does pdf analyze the function?

**Comment by trufae** [comment]
Pdf dowsnt anayzes anything. You need to use af. The commands starting with : are only specific to the io plugin. In this case r2frida, so :px does the hexdump using the frida apis instead of the r2 one. So its less fancy as you see.

to analyse just do af, like u normaly do in r2

**Comment by solitudecc** [comment]
thanks
