### ISSUE TITLE
Builds without nodejs

### ISSUE THREAD

**Issue by trufae** [nowsecure/r2frida#354]
NodeJS is a painful dependency for some users because:

* Debian have too old version
* Termux have too newer version
* frida-compile is expensive and some machines cant build it as fast as we wish

Proposed solution:

* Provide a precompiled version of the agent and just compile the C code

Some comments on this:

* This precompiled script can be shipped inside the same git or in a separate gist/release page.
* Do we want non-node builds to be the default? Autodetected? Disabled by default?
* The commited agent should be minified imho, if the user builds it debug info is useful.
* Must be tested in the CI

**Comment by radare** [comment]
Done in master. the only reamining part is to skip the cnofigure checks, maybe with an option flag disabled by default :?

**Comment by trufae** [comment]
Closing as its done
