### ISSUE TITLE
Add dx command to execute code in target process

### ISSUE THREAD

**Issue by trufae** [nowsecure/r2frida#36]
By default dx 0x804804804

will do the following:

```
(new NativeFunction('0x804804804', 'pointer', [])();
```

but it should handle the following things:

* Symbol resolution (`dx getuid`)
* Define function signature inline (`dx:ipi write 1 0x804804 10`)

NOTES

* dx in r2 accepts an hexpair of code to run.. this is not doing the same, so maybe we should use a different name for this command.
*

**Comment by radare** [comment]
This has been implemented in `dxc`.. the `dx` thing needs to be done still to mimic the same behaviour as r2

**Comment by trufae** [comment]
This is done already
