### ISSUE TITLE
Error using r2Frida

### ISSUE THREAD

**Issue by ferdinan4** [nowsecure/r2frida#372]
Hi there,

I am trying to use r2Frida in my MacBook M1. But, It fails when I tried to attached to any process:

`radare2 % R2_DEBUG=1 r2 frida://usb/
Cannot open directory '/opt/homebrew/Cellar/radare2/5.6.2/lib/radare2/5.6.2'
Loading /Users/fernando/.local/share/radare2/plugins/io_frida.dylib
PLUGIN LOADED 0x6000019800a0 fcn 0x1007c2fc0
Loading /Users/fernando/.local/share/radare2/plugins/asm_ghidra.dylib
PLUGIN LOADED 0x600001980640 fcn 0x1007c3128
Cannot open /Users/fernando/.local/share/radare2/plugins/r2ghidra_sleigh-5.6.2.zip
Loading /Users/fernando/.local/share/radare2/plugins/anal_ghidra.dylib
PLUGIN LOADED 0x600001980500 fcn 0x1007c30cc
Cannot open /Users/fernando/.local/share/radare2/plugins/r2ghidra_sleigh
Loading /Users/fernando/.local/share/radare2/plugins/core_ghidra.dylib
PLUGIN LOADED 0x600001980140 fcn 0x1007c3018
Cannot open directory '/opt/homebrew/Cellar/radare2/5.6.2/lib/radare2-extras/5.6.2'
Cannot open directory '/opt/homebrew/Cellar/radare2/5.6.2/lib/radare2-bindings/5.6.2'
[r] Cannot open 'frida://usb/'`

I can for example list the application in running in my devices, but I can't attached to them:

`fernando@D6PR73KY7H radare2 % r2 "frida://apps/usb//"
PID                            Name Identifier
----------------------------------------------

900                     SIM Toolkit com.android.stk
1425                         Google com.google.android.googlequicksearchbox
1425                         Google com.google.android.googlequicksearchbox
4358                         LOLita xyz.kwai.lolita.memes
4650                          Phone com.google.android.dialer
5046                       Settings com.android.settings
5174                       Messages com.google.android.apps.messaging
5606            Uncrackable Level 2 owasp.mstg.uncrackable2
6063                         Chrome com.android.chrome

[r] Cannot open 'frida://apps/usb//'`

All the commands end with. this sentence: **[r] Cannot open 'frida://apps/usb//'`**

Any idea?¿
Thanks in advance

**Comment by ferdinan4** [comment]
Solved :)

**Comment by klmitchell2** [comment]
Care to explain to us what the solution was @ferdinan4 ?
