### ISSUE TITLE
ERROR: Build failed

### ISSUE THREAD

**Issue by lwx7832** [nowsecure/r2frida#376]
![1111111111111111](https://user-images.githubusercontent.com/22617861/169700592-264f0270-80e1-46bf-a096-1c42bbe4b0c1.jpg)
Prompt build failed after installing with r2pm -ci r2frida

**Comment by trufae** [comment]
You are probably running an old version of radare2

**Comment by trufae** [comment]
Odd versions are git builds. This coreb was introduced in 2022-05-07. So if your build is before that date please update

**Comment by lwx7832** [comment]
Thank you. It has been built successfully, but there is a new problem. I can't connect my mobile phone with the command
<img width="588" alt="截屏2022-05-24 00 44 51" src="https://user-images.githubusercontent.com/22617861/169868658-52a7a61c-8469-407a-a9aa-ba09bd9f2644.png">

**Comment by trufae** [comment]
See r2 frida://? For sample uris. No need to specify the deviceid if theres only one device connected
