### ISSUE TITLE
Implement watchpoints

### ISSUE THREAD

**Issue by trufae** [nowsecure/r2frida#45]
* change memory protections with Memory.protect()
* hook the setExceptionHandler() and catch if it's R,W,X and the address matches.

Ole André Vadla Ravnås, [19 Feb 2017 01:46]: 

(on top of Memory.protect() and Process.setExceptionHandler())

only part I don't like is that Process.setExceptionHandler() is just a single handler obviously
so it would be nice to have API that has a chain of handlers
where they're called in order

**Comment by iddoeldor** [comment]
@ghostkkk any update ?

**Comment by trufae** [comment]
closing as dup for https://github.com/nowsecure/r2frida/issues/496 and may be helpful to keep it here for our future selfs when implementing it
