### ISSUE TITLE
'search string' module doesn't show any results

### ISSUE THREAD

**Issue by Gitdork** [nowsecure/r2frida#497]
when i use search strings function ,no matter what strings i search ,i just don't have any results 

frida:16.0.19 radare:5.8.9 r2frida:5.8.8 

└─$ r2 frida://spawn/usb/FA71J0301053/Diva
 -- ♥  --
[0x00000000]> :/?
:/ [str]                  search string passed as argument
:/i [type]                search instances of given type
:/v1                      search 1 byte of given numeric value
:/v2                      search 2 byte (little endian) number in memory
:/v4                      search 4 byte (dword, 32bit LE value in memory)
:/v8                      search 8 byte (qword 64bit LE value)
:/w [str]                 same as / but for wide strings (utf16)
:/x [hexstr]              find hexadecimal string
[0x00000000]> :/ a
Searching 1 bytes: 61
hits: 0

[0x00000000]> :/ b
Searching 1 bytes: 62
hits: 0

[0x00000000]> \/ a
ERROR: Invalid command '\/ a' (0x5c)

[0x00000000]> :/j a
Searching 1 bytes: 61
hits: 0
[]
[0x00000000]> :/j b
Searching 1 bytes: 62
hits: 0
[]

**Comment by trufae** [comment]
That’s expected, as long as you are in the offset 0 r2frida doesnt know where you want to search for that stuff. See the :e  options to specify the boundaries or :init to get that shaped properly (and seek to the module you are in)

**Comment by trufae** [comment]
that put a dot before the :e/ to run these commands otherwise this command wont do anything. just tested it and works perfectly fine

**Comment by Gitdork** [comment]
> that put a dot before the :e/ to run these commands otherwise this command wont do anything. just tested it and works perfectly fine

do you mean   '.:/e' ?

**Comment by trufae** [comment]
No /e is not the same as e/
