### ISSUE TITLE
Duplicates in \is

### ISSUE THREAD

**Issue by alvarofe** [nowsecure/r2frida#50]
```
alvaro@alvaro:~$ r2 frida://cat                           
Warning: r2frida cannot initialize mjolner
fstat : Error: expected a pointer
 -- 255 shades of (truecolor) grey
[0x00000000]> \is write
0x7f51d5666cc0
0x7f51d4e13620
0x7f51d5666cc0
0x7f51d4e13620
0x7f51d5666cc0

```

I would add modules as well in the output.

**Comment by trufae** [comment]
the reason for having more than one  line here is because the symbol is defined in more than one module. But i agree on that’s confusing

**Comment by trufae** [comment]
The behaviour of is and many otoher commands have changed to be more consistent. so this shouldnt be an issue anymore
