### ISSUE TITLE
`:dl` with no args it should show up help instead of an ERROR

### ISSUE THREAD

**Issue by enovella** [nowsecure/r2frida#508]
![image](https://github.com/nowsecure/r2frida/assets/14809754/98a2776d-625b-4d47-87eb-1f5e00bccead)

**Comment by trufae** [comment]
should be fixed in master now

**Comment by trufae** [comment]
Are you sure you are using the last build of r2frida? Because there are warnings of abi incompatible plugins and i cant repro
