### ISSUE TITLE
Static analysis apparently fails when running r2frida on Linux

### ISSUE THREAD

**Issue by suidpit** [nowsecure/r2frida#521]
I'm trying to use r2frida to perform both static/dynamic analysis on a target process on Linux.
However, all the commands that usually work with "plain" r2 seem to fail when using frida.

Example:
![image](https://github.com/nowsecure/r2frida/assets/25264901/e43e880f-e853-48ba-9e4f-4c2675957593)

It really seems I am making some mistakes with the API, but it seems the session is borked for some reason.
r2 version: 5.8.8-667-g0ae85c519b
r2frida latest.

**Comment by nitanmarcel** [comment]
r2frida is mostly used for dynamic analysis, what you can do is do the static analysis in r2 and seek to the symbol in r2frida. List your libraries and get the base offset of the library you want, and seek to the symbol with `s base_offset + offset

**Comment by nitanmarcel** [comment]
ah and don't forget to do `:is.` after seeking

**Comment by as0ler** [comment]
The latest build of `radare2` and `r2frida` is running `.:init` by default which imports some dynamic information to the r2 session.

However, if you want to import symbols, you can run `.:is*`.

**Comment by trufae** [comment]
You may want to try it again, all those symbol and basic autoanalysis is done now by default, so i think the experience has improved since then. Closing the ticket but feel free to share some comments at any time
