### ISSUE TITLE
question about agent.js in release

### ISSUE THREAD

**Issue by AkaShrug** [nowsecure/r2frida#533]
![image](https://github.com/nowsecure/r2frida/assets/39406056/f45984a1-4427-4f14-929c-d8744745e7c1)
is it normal for all agent in releases since 5.8.0 to have weird symbols at top or is this issue with github/browser?

**Comment by trufae** [comment]
Thats a compiled esm script. Thats how frida-compile builds the agent since then. Its like two times faster than shipping requirejs and loading the whole minified javascript and the final file is much smaller too. So yes its normal
