### ISSUE TITLE
Enhance: `:dt-*` - clear all traces command is hard to find

### ISSUE THREAD

**Issue by enovella** [nowsecure/r2frida#541]
![image](https://github.com/nowsecure/r2frida/assets/14809754/8ef690b1-e485-42d8-9c8b-1406e3c4a81c)

**Comment by as0ler** [comment]
What do you mean when saying it is hard to find?

**Comment by trufae** [comment]
i think he means its not listed in the help message

**Comment by trufae** [comment]
Yes i see the same. But those are subcommands. Those shouldnt be even listed but you wanted there
