### ISSUE TITLE
Invalid command `oo` (0x1f)

### ISSUE THREAD

**Issue by enovella** [nowsecure/r2frida#542]
It happens randomly and frequently with any app I'd say:

![oo](https://github.com/nowsecure/r2frida/assets/14809754/cfc8b7ee-1dcb-4f1d-8ff4-672d08291441)

**Comment by trufae** [comment]
looks like 0x1f is an invalid character , this is not an 'o'. so check your history, keyboard, usb connection or terminal settings, because that bug have nothing to do with r2frida

**Comment by trufae** [comment]
Closing, as this makes no sense
