### ISSUE TITLE
`:i?` doesn't provide command description

### ISSUE THREAD

**Issue by enovella** [nowsecure/r2frida#548]
<img width="575" alt="Screenshot 2024-01-28 at 00 29 33" src="https://github.com/nowsecure/r2frida/assets/14809754/86581c73-7dbf-4c83-a092-a8038f99597d">

**Comment by trufae** [comment]
The output listed above is the help. Not sure if i understand your issue here

**Comment by trufae** [comment]
. J *… are command modifiers. Imho those shouldnt have any help and must be displayed with brackets. I will merge this for now, but only commands and subcommands should be listed there
