### ISSUE TITLE
`:dmm`: ERROR: error: cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by enovella** [nowsecure/r2frida#549]
<img width="963" alt="Screenshot 2024-01-28 at 00 39 50" src="https://github.com/nowsecure/r2frida/assets/14809754/7ec1866f-dd47-4e32-9e1b-6fd35eff2f06">

**Comment by trufae** [comment]
its not about tweak. those errors should be fixed. working on it rn

**Comment by trufae** [comment]
btw, always specify the target os/arch. because this is a linux specific bug
