### ISSUE TITLE
Tweak `.:init*` at process injection to avoid showing a lot of errors

### ISSUE THREAD

**Issue by enovella** [nowsecure/r2frida#550]
<img width="742" alt="Screenshot 2024-01-28 at 00 46 19" src="https://github.com/nowsecure/r2frida/assets/14809754/956a1f14-cbd0-488c-9a51-884e22563f92">

**Comment by trufae** [comment]
try again with master and confirm the bug is fixed

**Comment by trufae** [comment]
Guess thats because java apps have no entry0?

**Comment by trufae** [comment]
try again, i did a blind fix, ill try to setup an android device and do further testing
