### ISSUE TITLE
Android: `wa ret` is not allowed in R2Frida session. `error: expected a pointer`

### ISSUE THREAD

**Issue by enovella** [nowsecure/r2frida#557]
More info & sample at: https://github.com/nowsecure/r2frida/issues/556

# Problem

We cannot perform in-memory patching

![image](https://github.com/nowsecure/r2frida/assets/14809754/44e417b0-9bf0-41fc-8e55-fe54931604c6)

# Old slides with right inmem patching
![image](https://github.com/nowsecure/r2frida/assets/14809754/2fa9d699-ac36-401a-bbde-dabc08d4d1d2)

# More info
```sh
[0x751067cad4]> wa ret
ERROR: error: expected a pointer
ERROR: Cannot write. Use `omf`, `io.cache` or reopen the file in rw with `oo+`
[0x751067cad4]> wx c0035fd6
ERROR: error: expected a pointer
ERROR: Cannot write. Use `omf`, `io.cache` or reopen the file in rw with `oo+`
[0x751067cad4]> wx 0xc0035fd6
ERROR: error: expected a pointer
ERROR: Cannot write. Use `omf`, `io.cache` or reopen the file in rw with `oo+`
[0x751067cad4]>
```

# Memory permissions: :dmp failing 
![image](https://github.com/nowsecure/r2frida/assets/14809754/b23139a3-cb8f-4a2e-8dda-948ba122dd39)

**Comment by trufae** [comment]
if io.cache is enabled then you are not patching anything. on linux, mac and ios all these commands works fine, , wa, wx and dmp work as it should

**Comment by as0ler** [comment]
It worked running Android 12 and Frida 16.1.10: (with io.cache=false)

![image](https://github.com/nowsecure/r2frida/assets/11234807/e591b13f-ec83-4e7e-ab99-102035384a5a)

**Comment by as0ler** [comment]
:dmp working on Android 12 running Frida 16.1.11:

![image](https://github.com/nowsecure/r2frida/assets/11234807/6a753d89-e146-4f14-9f07-eaf02e8eefd4)
