### ISSUE TITLE
Check maps before setting the breakpoint

### ISSUE THREAD

**Issue by trufae** [nowsecure/r2frida#56]
To avoid users think it's a Frida problem that is not able to set a breakpoint on a non-allocated page, and show proper issue when doing it non-executable regions

**Comment by trufae** [comment]
dbg.inmaps is set by default, but r2frida doesnt exposes the maps to r2, so it must be disabled manually to use breakpoints

**Comment by radare** [comment]
e dbg.inmaps=false ?

**Comment by dennykong** [comment]
yes it is
e dbg.bpinmaps=false

**Comment by trufae** [comment]
Done already because it tries to grab the current Module associated with the breakpoint/trace you set
