### ISSUE TITLE
make report error

### ISSUE THREAD

**Issue by pzwwei** [nowsecure/r2frida#58]
xxd -i < src/_agent.js > src/_agent.h
cc -c -fPIC -I/usr/local/include/libr -DWITH_CYLANG=0 -Iext/frida src/io_frida.c -o src/io_frida.o
src/io_frida.c:72:13: warning: implicit declaration of function 'r_str_appendf' is invalid in C99
      [-Wimplicit-function-declaration]
                newfile = r_str_appendf (newfile, "%s.js", str);
                          ^
src/io_frida.c:72:11: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int'
      [-Wint-conversion]
                newfile = r_str_appendf (newfile, "%s.js", str);
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
pkg-config --cflags r_core
-I/usr/local/include/libr
c++ src/io_frida.o -o io_frida.dylib -shared -fPIC -L/usr/local/lib -lr_core -lr_config -lr_cons -lr_io -lr_util -lr_flag -lr_asm -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_socket -lr_fs -lr_magic -lr_crypto -Wl,-no_compact_unwind ext/frida/libfrida-core.a -lresolv -framework Foundation -lbsm -framework AppKit
Undefined symbols for architecture x86_64:
  "_r_str_appendf", referenced from:
      _slurpFile in io_frida.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [io_frida.dylib] Error 1
make: *** [all] Error 2

**Comment by trufae** [comment]
Update r2 from git

**Comment by pzwwei** [comment]
Thanks , I have updated the r2. When i run the command :192:r2frida pzwwei$ r2 frida://92692.
has remind me : Cannot open 'frida://92692'. 
Here is the log:
```
radare2 1.4.0-git 14306 @ darwin-x86-64 git.1.3.0-210-ga6e87ff
commit: a6e87ff6df775be0f06002249dde7206a3074976 build: 2017-03-29__21:59:05
192:r2frida pzwwei$ frida help
     ____
    / _  |   Frida 9.1.23 - A world-class dynamic instrumentation framework
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to attach: unable to find process with name 'help'
192:r2frida pzwwei$ r2 frida://92692
Cannot open 'frida://92692'
```

**Comment by radare** [comment]
Does it works with normal frida? Are you sure the r2frida plugin is installed and listed in r2-L? Use R_DEBUG=1 env var to see whats going on

**Comment by pzwwei** [comment]
It seems to be work in normal frida.
```
pzwwei:r2frida pzwwei$ frida-ls-devices
Id                                        Type    Name
----------------------------------------  ------  ------------
local                                     local   Local System
e8bf3e68a322a77c9502947d9670a6fd263f007f  tether  iPhone
tcp                                       remote  Local TCP

pzwwei:r2frida pzwwei$ frida-ps -U
PID  Name
---  ----------------
697  App Store
665  Safari
654  设置
413  邮件

```
How to install r2frida plugin? I just clone r2frida project to make.
I thought I was missing some steps:
First I install radare2 use git (http://github.com/radare/radare2)
Second I clone (git clone https://github.com/nowsecure/r2frida.git) and cd to the r2frida dir to make.
