### ISSUE TITLE
 Neither source directory 'w' nor build directory None contain a build file meson.build.

### ISSUE THREAD

**Issue by mriamnobody** [nowsecure/r2frida#587]
# Platform and tools details

OS: Windows 11
Visual Studio 2022 Community edition
Python v3.10.7
Build Environment: x64
Meson Version: 1.4.0
r2frida: v5.9.0
radare2: v5.9.0

# Issue
I have first downloaded the above mentioned versions of `r2frida` **(git cloned r2frida repository)** and `radare2` **(downloaded release)**. Extracted `radare2-x.y.z` and renamed it to `radare2`. Place `radare2` folder **(to avoid any issues I also placed the contents of `radare2` inside the `r2frida` folder`)** inside the `r2frida` folder and ran `preconfigure.bat` and got output:

```
=== Finding Git...
OK
Already up to date.
=== Finding Visual Studio...
"Found 2022 Community edition"
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.6.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
```

After that I executed `configure.bat` and for that I got error:
```
"Configuring the build directory with cmake"

ERROR: Neither source directory 'w' nor build directory None contain a build file meson.build.
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
**EDIT 1**: You don't have to run `configure.bat`. To successfully build `r2frida` from source on Windows, you can make changes to `preconfigure.bat` and `make.bat` as mentioned in the PRs below (**Note** that these PRs were pending for approval as of the time of writing this edit).

https://github.com/nowsecure/r2frida/pull/590
https://github.com/nowsecure/r2frida/pull/589
https://github.com/nowsecure/r2frida/pull/591

**EDIT 2**: Even after successfully building `r2frida` from source or even using pre-built `r2-frida` it doesn't work. [Here](https://github.com/nowsecure/r2frida/issues/593) is the issue raised for the same.

**Comment by trufae** [comment]
Didnt u fixed it in the PRs?

**Comment by mriamnobody** [comment]
> Didnt u fixed it in the PRs?

I'm sorry for any confusion. The PRs I made fixed some of the minor issues that arose while building `r2-frida` from source.

This issue I'm facing, occurs when trying to launch `r2-frida`
