### ISSUE TITLE
Struggling for months to make this tool work either on Kali or in Windows

### ISSUE THREAD

**Issue by Abdelrahmanamhawy** [nowsecure/r2frida#620]
Kali : 
Running r2pm -ci r2frida i get a hell lot of errors that i tried for days fixing with no success. 

<img width="254" alt="2024-09-07_19-59" src="https://github.com/user-attachments/assets/a9e5f444-f955-4fdf-b99e-76161e1bdfba">

Strangly windows have less error . I downloaded the .zip file from release and have radare2 in the r2frida project folder . But i can't run it . When i run ./r2frida-compile.exe i get this error : 

<img width="656" alt="2024-09-07_19-58" src="https://github.com/user-attachments/assets/6cb1cf61-cc4a-422c-8846-a3ae4cd10fcb">

Please assist me with windows since i lost all hope on Kali . I don't know what to do anymore..

**Comment by trufae** [comment]
The error on kali is because (i guess) you i stalled r2 from the debian package and you didnt installed the -dev one so pkgconfig cant find the rcore library

the windows error is really weird because this symbol is in rutil.dll so i guess you forgot to copy the library in the same dieectory of the executable

**Comment by Abdelrahmanamhawy** [comment]
Okay so from scraping the responses here i saw that you advise people on uninstall r2 and installing , i did that and it now works ! Thanks . I have been struggling for days trying to find a tool that lets me debug ASM code in an APK directly , i have to bypass shielding . Anyways , thanks so much and hopefully it helps me :)

**Comment by trufae** [comment]
Happy to help and glad it works! Feel free to join the discord chat if you have more questions
