### ISSUE TITLE
Cannot compile: missing libxxhash-dev dependencies

### ISSUE THREAD

**Issue by cosad3s** [nowsecure/r2frida#637]
After installing all the dependencies on Kali Linux, following the README file, I got an error on compilation of r2frida (in the `configure` part):

```bash
❯ ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/usr/local'
checking for pkg-config... /usr/bin/pkg-config
checking for c compiler... gcc
checking exec r2 -v... ok
Using PKGCONFIG: /usr/bin/pkg-config
checking pkg-config flags for r_core... no
This package is required
```
After some investigation, it appears that the following line in `configure` returns an error: 

![image](https://github.com/user-attachments/assets/624c2b0d-786c-47f2-80f4-61cabcfc310c)

Indeed:

![image](https://github.com/user-attachments/assets/23af44a9-c868-4549-af4a-a6d1253d81d7)

Same behavior with `r2pm` for the installation.

```bash
❯ radare2 -v
radare2 5.9.4 0 @ linux-x86-64
birth: git.5.9.4 2024-10-24__09:10:25
options: gpl release -O1 cs:5 cl:2 meson
❯ uname -a
Linux kali 6.11.2-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.11.2-1kali1 (2024-10-15) x86_64 GNU/Linux
```

I had to do: `sudo apt install libxxhash-dev` to get the compilation of r2frida to work.  
I suggest to add this dependency in the requirements.

**Comment by trufae** [comment]
You need to install libradare2-dev to have the pkgconfig files on debian

**Comment by trufae** [comment]
Thats up to the debian distro. No other distro links to libxxhash, and actually its a bug in the debian package because it should be installing it as a dependency of libradare2-dev

**Comment by trufae** [comment]
Can you open a ticket in Debian?
