### ISSUE TITLE
Can't find OpenSSL includes on macOS High Sierra

### ISSUE THREAD

**Issue by tanis2000** [nowsecure/r2frida#77]
It looks like the install process can't find the OpenSSL includes on macOS High Sierra. Here's the log:

```
$ r2pm install r2frida
syntax error: error in error handling
syntax error: error in error handling
syntax error: error in error handling
Already up-to-date.
Install Done For r2frida
[ "`readlink ext/frida`" = frida-macos-10.6.13 ] || \
		(cd ext && rm -f frida ; ln -fs frida-macos-10.6.13 frida)
make io_frida.dylib
cc -c -fPIC -I/usr/local/Cellar/radare2/2.0.1/include/libr -DWITH_CYLANG=0 -Iext/frida src/io_frida.c -o src/io_frida.o
In file included from src/io_frida.c:3:
In file included from /usr/local/Cellar/radare2/2.0.1/include/libr/r_core.h:6:
/usr/local/Cellar/radare2/2.0.1/include/libr/r_socket.h:28:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [src/io_frida.o] Error 1
make: *** [all] Error 2
ERROR: Build failed
```

**Comment by trufae** [comment]
This seems to be an issue with the pkgconfig files of r2. Usually few people builds r2 with openssl as dependency, so the .pc files doesnt add the CFLAGS/LDFLAGS for that. Not sure if r2frida will work with last r2 release. so ideally i would recommend to install r2 from git, but ill fill an issue in r2 to track and solve this.

Thanks

**Comment by tanis2000** [comment]
I'm using the r2 that can be downloaded through Homebrew... it's version 2.0.1 and it looks like the latest release at the time I'm writing this. 
I'll have a go with the git version of r2 and see if anything changes. Cheers!

**Comment by trufae** [comment]
Should be fixed in here https://github.com/radare/radare2/commit/75066808c779d1541a0ccf42f46b8e60863f8ec3

so r2-2.1 will work fine if installed from brew with r2frida

thanks for reporting!
