### ISSUE TITLE
rp2m install fails

### ISSUE THREAD

**Issue by dacoursey** [nowsecure/r2frida#83]
Trying to get this installed on a new laptop and running into this problem I've never had before. I see the same error on some old issues, but those solutions don't seem to apply to me.

```
(frida) homembp:radare2 dc$ r2 -version
radare2 2.5.0-git 17625 @ darwin-x86-64 git.2.4.0-52-g1c1cad1d9
commit: 1c1cad1d9471776214646110042d6939a35284f3 build: 2018-03-08__21:37:37
(frida) homembp:radare2 dc$ r2pm -i r2frida
Already up-to-date.
Install Done For r2frida
Makefile:1: config.mk: No such file or directory
./configure
checking build system type... x86_64-unknown-darwin
checking host system type... x86_64-unknown-darwin
checking target system type... x86_64-unknown-darwin
checking for working directories... current
using prefix '/usr/local'
checking for c compiler... gcc
checking for c++ compiler... g++
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... no
This package is required
make: *** [config.mk] Error 1
ERROR: Build failed
(frida) homembp:radare2 dc$ 
```

**Comment by radare** [comment]
Do you have pkg-config installed?

**Comment by dacoursey** [comment]
I did not, so I installed it with brew.  Then it said xz was missing, so I installed that but it couldn't link to the pkg-config I just installed.  

Ran `brew doctor` and there were tons of problems, something must have gone horribly wrong early on. I fixed all of those and the plugin installed perfectly.

Thanks for the help!

**Comment by trufae** [comment]
wat is rp2m ? :P

**Comment by Manouchehri** [comment]
Note to myself:

`brew install node pkg-config`
