### ISSUE TITLE
Not connecting and no error message when trying to connect to Android/Genymotion

### ISSUE THREAD

**Issue by christiancoleman** [nowsecure/r2frida#84]
I'm trying to connect to a Genymotion Android device. Any help is appreciated.

![image](https://user-images.githubusercontent.com/6051308/38229329-5e0160d0-36d6-11e8-9fdf-9ea4b3acb7f9.png)
![image](https://user-images.githubusercontent.com/6051308/38229347-6e84c726-36d6-11e8-999d-9e67e7183bc7.png)
![image](https://user-images.githubusercontent.com/6051308/38229442-c71e470e-36d6-11e8-87d0-24791b18c479.png)
![image](https://user-images.githubusercontent.com/6051308/38229464-e0d9394c-36d6-11e8-9281-7ee6f8b76e37.png)

**Comment by christiancoleman** [comment]
Seems to just hang after entering the r2 frida command. No indication of activity or any errors.

**Comment by trufae** [comment]
can't reproduce. are you using last version of r2 and last version of frida in the device?

**Comment by trufae** [comment]
tested this using usb and tcp, and no issues at all. Wonder why are you connecting thru tcp if it's listed in frida-ps -U (usb). see frida-ls-devices and use r2 frida://<deviceid> instead of <ip:port> (usb is faster than tcp)

**Comment by christiancoleman** [comment]
Thanks for the super quick response. I see the following when running frida-ls-devices. Not sure how I can switch genymotion to go from an IP connection to a USB one. Were you testing using genymotion too?

![image](https://user-images.githubusercontent.com/6051308/38259983-6de1885a-3734-11e8-9035-e2ae9dee35a3.png)

**Comment by christiancoleman** [comment]
Also, here are my versions.

![image](https://user-images.githubusercontent.com/6051308/38261344-ecf5fd58-3737-11e8-9bf5-ddddf1e05a1a.png)

**Comment by trufae** [comment]
Can you connect with Frida?

**Comment by christiancoleman** [comment]
That pushed me in the right direction. I was able to fix it. Thank you @trufae 

For other people if you share the same symptoms then you probably need to bind the frida-server on the genymotion app to a port that isn't being used by adb.

![image](https://user-images.githubusercontent.com/6051308/38345419-0e9c5c74-385d-11e8-94ef-d50da602e660.png)

https://github.com/frida/frida/issues/70

Using this I 'adb -e shell'd in and did ./frida-server -l 192.168.56.101:5556. Afterwards, frida --host=192.168.56.101:5556 and r2 frida://192.168.56.101:5556 worked.
