### ISSUE TITLE
error compile r2frida

### ISSUE THREAD

**Issue by muhammad2321** [nowsecure/r2frida#85]
r2pm install r2frida                                                       
Already up to date.
Install Done For r2frida
Makefile:1: config.mk: No such file or directory
./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/usr/local'
checking for c compiler... gcc
checking for c++ compiler... g++
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... yes
checking for curl... /usr/bin/curl
checking for wget... /usr/bin/wget
checking for git... /usr/bin/git
checking for xz... /usr/bin/xz
checking for node... /usr/bin/node
checking for npm... no
error: This program is required.
Makefile:101: recipe for target 'config.mk' failed
make: *** [config.mk] Error 1

**Comment by trufae** [comment]
Try installing npm like the error message says
