### ISSUE TITLE
Multiple errors when connecting to a remote frida-server

### ISSUE THREAD

**Issue by redmed666** [nowsecure/r2frida#94]
Hello!

I have these kind of errors when connecting to a frida-server running on a Windows 10 VM (host is a MacOS):

```bash
r2 frida://172.16.172.86:5555/ConsoleApplication1.exe
setenv : Error: expected a pointer
getpid : Error: expected a pointer
getuid : Error: expected a pointer
dlopen : Error: expected a pointer
dup2 : Error: expected a pointer
__fxstat : Error: expected a pointer
close : Error: expected a pointer
kill : Error: expected a pointer
```

I can trace and do most of the stuffs (except for \i which gives "undefined not callable", retrieving symbols from libraries and maybe other things as well). But I'm wondering if it doesn't play a role with the different commands I can not do...

r2 version: radare2 2.8.0-git 18697 @ darwin-x86-64 git.2.4.0-1159-g4d91eb25e, commit: 4d91eb25e1eded7698d7d7146ca7fb533668aa79 build: 2018-07-10__07:47:34
frida version: {"version":"11.0.13"}

**Comment by mrmacete** [comment]
my gut feeling is those errors happen because we're trying to hook posix functions which aren't there on Windows.

i guess Windows support for r2frida needs some love. PRs welcome!

**Comment by redmed666** [comment]
That makes sense indeed!
Do you think this can be related to the fact that I can not get the symbols from a library when doing, for example, \is KERNEL32.DLL? I would presume that if there is an issue with "dlopen", it can not open the DLL and retrieve the symbols?

**Comment by mrmacete** [comment]
well no those are unrelated problems, if you pass a module name to `\is` make sure it's one of those listed by `\il` command (case sensitive)

**Comment by mrmacete** [comment]
oh and also try to use `\iE modulename` instead, beacause `enumerateSymbols()` Frida api isn't available on windows

**Comment by redmed666** [comment]
Ha indeed, working correctly like that. Thanks!

**Comment by trufae** [comment]
Will be good to get rid of those warnings on Windows, because we cant expect those symbols to be there, and support alternatives for that platform. Do you want to contribute this? Last windows i had at home was 20 years ago
