### ISSUE TITLE
MemoryAccessMonitor not available

### ISSUE THREAD

**Issue by redmed666** [nowsecure/r2frida#95]
Hi,

I've got this issue when trying to use MemoryAccessMonitor:

"MemoryAccessMonitor is not yet available in the Duktape runtime"

Can you maybe point where one could begin to dig to make this integration? And some guidelines to make it happen?

Thanks!

**Comment by oleavr** [comment]
There isn't yet any docs on how to add this kind of thing, so the best way to go about it is to look at the existing code while looking things up in Duktape's documentation.

I would start with a failing test to have a short feedback loop. For this particular feature there's already a test written, so all you have to do is enable it for Duktape too by removing [this](https://github.com/frida/frida-gum/blob/6f61184825b662f474e38afb82ae820f5e4e97ea/tests/gumjs/script.c#L4037-L4041) piece of code. Then run `gum-tests` with `-p /GumJS/Script/memory_access_can_be_monitored#DUK` so only that one test gets run. Once you have that, look at the MemoryAccessMonitor integration in our V8 [implementation](https://github.com/frida/frida-gum/blob/6f61184825b662f474e38afb82ae820f5e4e97ea/bindings/gumjs/gumv8memory.cpp#L1119-L1166). You can compare other implementation in Duktape vs V8 to see how the different things are done, and copy-paste/take inspiration from those.

**Comment by redmed666** [comment]
Thanks for your feedback, I will try to take a look at that :)

**Comment by redmed666** [comment]
Actually, there is something I'm not getting: MemoryAccessMonitor is supposed to be working on Windows right? In my case, I'm trying to inject it in a windows process so it should work, no? Or am I missing something?

**Comment by oleavr** [comment]
The monitor itself is only implemented on Windows. The reason it doesn't work is that our Duktape runtime is the default, and only the V8 runtime has `MemoryAccessMonitor` exposed.

**Comment by michalfapso** [comment]
I had the same error. Try to run Frida with `--enable-jit`, it worked for me.

**Comment by trufae** [comment]
V8 is the default runtime in r2frida. You shouldnt be having this problem now

**Comment by michalfapso** [comment]
Thanks, @trufae. I am sorry, I didn't notice that this issue is in the r2frida project. I thought it is for Frida.
