### ISSUE TITLE
r2frida spawn don't work?

### ISSUE THREAD

**Issue by ghostkkk** [nowsecure/r2frida#98]
Hi guys,

I'm trying to spawn in a process with R2frida.

try command

r2 frida://028f1f3c0a539153//com.xxx.xxxx

but, The next message appeared.

"Cannot spawn: The 'argv' option is not supported when spawning Android apps"

hum.. may not supported in current version.. right?

Test Environment
frida-server-12.1.1-android-arm in Android OS
r2frida [0x00000000]> ?V 2.7.0 105 in Mac Os

**Comment by enovella** [comment]
Hi @ghostkkk,

Some questions to spot your problem:
- Did you forward the port 27042?
- Can you try to show the Frida version with   `\?V`?
- Did you try with previous versions of Frida? Try that by installing previous versions via `pip`.
- Are you using the latest `r2frida` release?

Cheers

**Comment by ghostkkk** [comment]
frida server          : V 12.1.1
frida tools client   : V 12.1.1
r2frida                 : V 2.7.0 105 in Mac Os

The installed version is the latest version.

And... Google search result... It was also found in the source on the github.

https://github.com/frida/frida-core/blob/master/src/linux/linux-host-session.vala

213 line in frida-core/src/linux/linux-host-session.vala 
  
	if (options.has_argv)
		throw new Error.NOT_SUPPORTED ("The 'argv' option is not supported when spawning Android apps");


Perhaps i think, remote spawn is not implemented in the Android version.

**Comment by enovella** [comment]
Ok, I can reproduce that and know how to fix it. @mrmacete told me what to comment out.
It will be pushed soon no worries.

**Comment by enovella** [comment]
It should be fixed in https://github.com/nowsecure/r2frida/pull/103.

**Comment by trufae** [comment]
🎉

**Comment by ghostkkk** [comment]
oh~~.. thank for your feedback.

**Comment by enovella** [comment]
@ghostkkk please close the issue ;)
